name: "anxibits"
description: "Random encounters of rage and fun"
author: "Jxnblk"

highlighter: pygments
markdown: redcarpet

url: "http://aerosol.github.io/anxibits"

exclude: [README.md, Rakefile]
paginate: 16
permalink: /:title
